### PR TITLE
ENH: LivePlotWithGoal so we can plot the data from the centroid …

### PR DESCRIPTION
**Pull request by hhslepicka**
...and also show the target pixel and tolerance area.

unknown-8

Template notebook will be updated with the following PR: https://github.com/slaclab/Skywalker-Runs/pull/3

Example Run with Simulation: https://nbviewer.jupyter.org/gist/hhslepicka/c0581b5d784501e628474fcafd5fa86d

### CODE REVIEW

**Comment by teddyrendahl** [comment]
Can you also add this into the Jupyter Notebook for the simulation mode?

**Comment by hhslepicka** [comment]
@teddyrendahl I did... it is here: https://github.com/slaclab/Skywalker-Runs/pull/3

**Comment by teddyrendahl** [comment]
Think this looks good!

**Comment by hhslepicka** [comment]
Thank you @teddyrendahl 👍

**Pull request merged**
